# Generated by Django 5.0.7 on 2024-08-03 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_members'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notices',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sendername', models.CharField(max_length=20)),
                ('receivername', models.CharField(max_length=20)),
                ('details', models.TextField()),
                ('mobile', models.BigIntegerField()),
                ('datetime', models.DateTimeField()),
            ],
        ),
    ]
