# Generated by Django 5.0.7 on 2024-08-05 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_transactions'),
    ]

    operations = [
        migrations.CreateModel(
            name='Watchmans',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(max_length=20)),
                ('lastname', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=254)),
                ('city', models.CharField(max_length=20)),
                ('state', models.CharField(max_length=20)),
                ('mobile', models.BigIntegerField()),
                ('joiningDate', models.DateField()),
                ('dayshift', models.CharField(max_length=20)),
            ],
        ),
    ]
