# Generated by Django 5.0.7 on 2024-08-06 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_visitors'),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('eventname', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=254)),
                ('eventdate', models.DateTimeField()),
                ('description', models.TextField()),
                ('mobile', models.BigIntegerField()),
            ],
        ),
    ]
