# Generated by Django 5.0.7 on 2024-07-30 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AddNotice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('aboutnotice', models.TextField()),
                ('date', models.DateTimeField()),
                ('mobile', models.BigIntegerField()),
            ],
        ),
    ]
