# Generated by Django 5.0.7 on 2024-07-31 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_addnotice'),
    ]

    operations = [
        migrations.CreateModel(
            name='AddEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('eventname', models.CharField(max_length=20)),
                ('eventdetail', models.CharField(max_length=100)),
                ('datetime', models.DateTimeField()),
                ('mobile', models.BigIntegerField()),
            ],
        ),
    ]
