# Generated by Django 5.0.6 on 2024-06-27 10:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='product_master',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pname', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='sub_product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.IntegerField()),
                ('image', models.ImageField(upload_to='product_images/')),
                ('pmodel', models.CharField(max_length=100)),
                ('ram', models.CharField(max_length=100)),
                ('pname', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.product_master')),
            ],
        ),
    ]
